server:
  port: 8401

spring:
  application:
    name: cloudalibaba-sentinel-service
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.190.246:8848
    sentinel:
      transport:
        dashboard: 172.22.190.169:8858
        port: 8719
        clientIp: 172.22.190.34

management:
  endpoints:
    web:
      exposure:
        include: "*"
