server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 172.22.190.246:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'